### ISSUE TITLE
Parsing tests fail during build attempt

### ISSUE THREAD

**Issue by jame** [einhverfr/PGObject-Util-PseudoCSV#1]
As noted also at rt.cpan.org bug # [108416](https://rt.cpan.org/Public/Bug/Display.html?id=108416);  which associates it with which version of the PGObect module is being run;  parsing tests are failing at least with versions of PGObject at 1.402.9.

In my case; I found this when doing a test build of its Debian package  under the current Debian testing ('stretch'). which currently has PGObject (llibpgobject-perl) version 1.402.9 under Perl version v5.22.
See attached file for the results there of running **make test**:
[BuildErrors.txt](https://github.com/einhverfr/PGObject-Util-PseudoCSV/files/477254/BuildErrors.txt)

**Comment by einhverfr** [comment]
Should be fixed with latest version (2.0) to be released shortly.  I just removed the PGObject dependency.

**Comment by einhverfr** [comment]
As more info, 2.0 has a major backwards-breaking change which removes the auto-deserialization.  This means we don't need any other dependencies.  It means the module can be used more places.  And it means the test failures are easier to address.

**Comment by einhverfr** [comment]
2.0 uploaded to PAUSE.  On to closing the RT ticket as well.
