### ISSUE TITLE
Spelling error in lib/PGObject/Util/PseudoCSV.pm

### ISSUE THREAD

**Issue by jame** [einhverfr/PGObject-Util-PseudoCSV#2]
While working on the Debian packaging for the module, the following minor spelling error was found; an instance of the word *unnecessary* instead being spelled as *unecessary*, See also attached patch: 
[SpellingErrors.txt](https://github.com/einhverfr/PGObject-Util-PseudoCSV/files/2090596/SpellingErrors.txt)

**Comment by einhverfr** [comment]
fixed
